from datetime import datetime
from typing import Protocol

from .models import StarboardEntry


class StarboardRepository(Protocol):
    async def create(self, message: StarboardEntry) -> None: ...

    async def find(self, original_message_id: int) -> StarboardEntry | None: ...

    async def update_reaction_count(self, message_id: int, reaction_count: int) -> None: ...

    async def get_pending_updates(self, cutoff_time: datetime) -> list[StarboardEntry]: ...

    async def set_starboard_message_id(self, original_message_id: int, starboard_message_id: int) -> None: ...
